# Parameters used to generate this project with aem-project-archetype

groupId=com.shimano.gdam1
artifactId=shimano-gdam-1
version=1.0.0-SNAPSHOT
package=com.shimano.gdam1
appId=shimano-gdam-1
appTitle=Shimano GDAM 1
aemVersion=cloud
sdkVersion=latest
languageCountry=${languageCountry}
includeExamples=n
includeErrorHandler=n
frontendModule=general
singleCountry=n
includeDispatcherConfig=n
includeCif=n
includeForms=n
includeFormsenrollment=n
includeFormscommunications=n
sdkFormsVersion=latest
commerceEndpoint=https://hostname.com/graphql
datalayer=y
amp=n
enableDynamicMedia=y
enableSSR=n
precompiledScripts=n
includeFormsheadless=n
